# Render 部署配置 (最终版 - 已指定地区)
services:
  # FastAPI 后端服务
  - type: web
    name: thinktree-backend
    env: python
    plan: free
    region: singapore # <--- 关键修改：明确指定地区为新加坡
    buildCommand: cd backend && pip install -r requirements.txt
    startCommand: cd backend && alembic upgrade head && uvicorn main:app --host 0.0.0.0 --port $PORT
    healthCheckPath: /health
    envVars:
      - key: GEMINI_API_KEY
        sync: false
      - key: SECRET_KEY
        sync: false
      - key: DATABASE_URL
        fromDatabase:
          name: thinktree-db
          property: connectionString
      # ... 其他 envVars ...

  # Next.js 前端服务
  - type: web
    name: thinktree-frontend
    env: node
    plan: free
    region: singapore # <--- (推荐) 最好也将前端服务放在同一地区
    buildCommand: cd frontend && npm install && npm run build
    startCommand: cd frontend && npm start
    healthCheckPath: /api/health
    envVars:
      - key: NEXT_PUBLIC_API_URL
        value: https://thinktree-backend.onrender.com
      # ... 其他 envVars ...

# PostgreSQL 数据库
databases:
  - name: thinktree-db
    plan: free
    region: singapore # 确认数据库也在新加坡
