"""Add magic_token to login_tokens table

Revision ID: 0b01e30b6947
Revises: 5c70a4153e2c
Create Date: 2024-07-31 12:00:00.000000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0b01e30b6947'
down_revision = '5c70a4153e2c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('login_tokens', sa.Column('magic_token', sa.String(length=255), nullable=True))
    op.create_index(op.f('ix_login_tokens_magic_token'), 'login_tokens', ['magic_token'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_login_tokens_magic_token'), table_name='login_tokens')
    op.drop_column('login_tokens', 'magic_token')
    # ### end Alembic commands ### 