"""Add login_tokens table

Revision ID: 5c70a4153e2c
Revises: b2b68aa4d765
Create Date: 2024-07-31 10:00:00.000000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5c70a4153e2c'
down_revision = 'b2b68aa4d765'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('login_tokens',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('code_hash', sa.String(length=255), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('used_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_login_tokens_email'), 'login_tokens', ['email'], unique=False)
    op.create_index(op.f('ix_login_tokens_id'), 'login_tokens', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_login_tokens_id'), table_name='login_tokens')
    op.drop_index(op.f('ix_login_tokens_email'), table_name='login_tokens')
    op.drop_table('login_tokens')
    # ### end Alembic commands ###
