"""Add invitation_code to login_tokens

Revision ID: 8c6bf939bde7
Revises: 0b01e30b6947
Create Date: 2025-08-03 13:51:42.337544

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8c6bf939bde7'
down_revision: Union[str, Sequence[str], None] = '0b01e30b6947'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Add invitation_code column to login_tokens table."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('login_tokens', sa.Column('invitation_code', sa.String(length=16), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Remove invitation_code column from login_tokens table.""" 
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('login_tokens', 'invitation_code')
    # ### end Alembic commands ###