"""Add invitation_code to login_tokens table

Revision ID: 7b8f9d2e1a3c
Revises: 10a5e7b2f968
Create Date: 2025-08-03 13:30:00.000000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7b8f9d2e1a3c'
down_revision = '10a5e7b2f968'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('login_tokens', sa.Column('invitation_code', sa.String(length=16), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('login_tokens', 'invitation_code')
    # ### end Alembic commands ###